name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install -r requirements.txt
    - name: Dummy step
      run: |
        echo "Wszystko gra!"
    - name: Analysing the code with pylint
      continue-on-error: true
      run: |
        pylint $(git ls-files '*.py')
    - name: Run unit tests
      run: |
         pytest ksiazka
  sonar:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Testowanie kodu przez Sonara
      run: |
        echo "Sonar ok"
  deployment:
    needs: [build, sonar]
    runs-on: ubuntu-latest
    steps:
    - name: Deployment na Deva
      run: |
        echo "Deployment na deva udany"        
